# Generated by Django 2.1.1 on 2018-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.CharField(default='n\na', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(default='n\na', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default='n\na', max_length=15),
        ),
    ]
